#!/bin/sh
#   _________  __   ___  __ _____   _  _____  ____
#  / ___/ __ \/ /  / _ \/ // / _ | / |/ / _ \/ __/
# / /__/ /_/ / /__/ // / _  / __ |/    / // /\ \  
# \___/\____/____/____/_//_/_/ |_/_/|_/____/___/ 
# coldhands.xyz
# 2021

##Autostart
$HOME/.config/bspwm/autostart.sh

##Bspwm configuration
#bspc config border_radius       8
bspc config border_width         1
bspc config window_gap           10
bspc config top_padding          30
bspc config bottom_padding       10
bspc config left_padding         10
bspc config right_padding        10
bspc config single_monocle       false
#bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true
#bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

##Bspwm coloring
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"
#bspc config urgent_border_color 	"#dd2727"

##Desktop names
bspc monitor -d I II III IV V

##Fullscreen applications
bspc rule -a Retroarch state=fullscreen

##Floating applications
bspc rule -a feh state=floating center=true
bspc rule -a Galculator state=floating center=true
bspc rule -a Gpick state=floating sticky=on
bspc rule -a Oblogout state=floating center=true
bspc rule -a Pavucontrol state=floating center=true
bspc rule -a Bitwarden state=floating sticky=on

##Open applications on specific workspaces
#bspc rule -a Subl3 desktop='II'
bspc rule -a Steam desktop='V'
bspc rule -a Io.github.celluloid_player.Celluloid desktop='V'
bspc rule -a discord desktop='IV'
#bspc rule -a Spotify desktop='V' follow=on

##Polybar hidden when fullscreen for vlc, youtube, mpv ...
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_eDP1)

##External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window

##Pywal
#source the colors.
. "${HOME}/.cache/wal/colors.sh"

##Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

## END OF LINE ##