#!/bin/sh

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh
#fix for moving spotify to specific workspace
#bspc config external_rules_command ~/.config/bspwm/scripts/external_rules_command

#BSPWM configuration
#bspc config border_radius       8
bspc config border_width         1
bspc config window_gap           10
bspc config top_padding          30
bspc config bottom_padding       10
bspc config left_padding         10
bspc config right_padding        10
bspc config single_monocle       false
#bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true
#bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM coloring
#bspc config normal_border_color		"#4c566a"
#bspc config active_border_color		"#1e1e1e"
#bspc config focused_border_color	"#5e81ac"
#bspc config presel_feedback_color	"#5e81ac"
#bspc config urgent_border_color 	"#dd2727"


#Single monitor
bspc monitor -d I II III IV


#Fullscreen applications
bspc rule -a Spotify desktop=^4 follow=on state=fullscreen
bspc rule -a celluloid state=fullscreen
bspc rule -a retroarch state=fullscreen
bspc rule -a steam state=fullscreen


#Floating applications
bspc rule -a arandr state=floating
bspc rule -a feh state=floating
bspc rule -a font-manager state=floating
bspc rule -a galculator state=floating
bspc rule -a gpick state=floating sticky=on
bspc rule -a oblogout state=floating
bspc rule -a pavucontrol state=floating sticky=on
bspc rule -a rofi state=floating sticky=on
bspc rule -a bitwarden state=floating


#Tiled applications
bspc rule -a gnome-disks state=tiled
bspc rule -a xfce4-settings-manager state=tiled


###External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window

##Pywal
# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

# Spotify fix move desktop 4
. "${HOME}/.scripts/spotifyfix.sh"
